"""Add habilidades to Perfil

Revision ID: 0b5ef99c1b41
Revises: 812a918651a9
Create Date: 2026-06-20 18:41:38.761592
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0b5ef99c1b41'
down_revision: Union[str, None] = '812a918651a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perfiles', sa.Column('habilidades', sa.JSON(), server_default='[]', nullable=False), schema='oppy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('perfiles', 'habilidades', schema='oppy')
    # ### end Alembic commands ###
