"""add_image_and_link_to_habilitacion

Revision ID: 25caf90dc905
Revises: ee8e1b4aa8ec
Create Date: 2026-06-19 17:36:16.926759
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '25caf90dc905'
down_revision: Union[str, None] = 'ee8e1b4aa8ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habilitaciones', sa.Column('image_url', sa.String(length=500), nullable=True), schema='oppy')
    op.add_column('habilitaciones', sa.Column('enlace', sa.String(length=500), nullable=True), schema='oppy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habilitaciones', 'enlace', schema='oppy')
    op.drop_column('habilitaciones', 'image_url', schema='oppy')
    # ### end Alembic commands ###
