"""Add unread_referrals_count

Revision ID: 26f63778a77a
Revises: eeef772d434a
Create Date: 2026-06-29 15:29:30.198384
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '26f63778a77a'
down_revision: Union[str, None] = 'eeef772d434a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('unread_referrals_count', sa.Integer(), server_default='0', nullable=False), schema='oppy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'unread_referrals_count', schema='oppy')
    # ### end Alembic commands ###
