"""Add Gemini key and AI credits

Revision ID: 2719fae81faa
Revises: ff516055ba4d
Create Date: 2026-06-15 20:11:44.638852
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2719fae81faa'
down_revision: Union[str, None] = 'ff516055ba4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('encrypted_gemini_key', sa.String(length=2048), nullable=True), schema='oppy')
    op.add_column('usuarios', sa.Column('ai_credits', sa.Integer(), server_default='10', nullable=False), schema='oppy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'ai_credits', schema='oppy')
    op.drop_column('usuarios', 'encrypted_gemini_key', schema='oppy')
    # ### end Alembic commands ###
