"""Add referral_code to EmailConfirmationToken

Revision ID: 310c5fef5724
Revises: 26f63778a77a
Create Date: 2026-06-29 15:33:12.981700
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '310c5fef5724'
down_revision: Union[str, None] = '26f63778a77a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_confirmation_tokens', sa.Column('referral_code', sa.String(length=100), nullable=True), schema='oppy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_confirmation_tokens', 'referral_code', schema='oppy')
    # ### end Alembic commands ###
