"""Initial Schema

Revision ID: 34316ea4791d
Revises: 
Create Date: 2026-06-27 20:54:26.782421
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '34316ea4791d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
