"""initial_schema_uuid

Revision ID: 34a182dc639a
Revises: 
Create Date: 2026-06-22 16:55:27.999054
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '34a182dc639a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
