"""Add authentication fields to Usuario

Revision ID: 3b639b24b856
Revises: 78be53d3011b
Create Date: 2026-06-11 22:45:27.437064
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3b639b24b856'
down_revision: Union[str, None] = '78be53d3011b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('first_name', sa.String(length=100), nullable=True), schema='oppy')
    op.add_column('usuarios', sa.Column('last_name', sa.String(length=100), nullable=True), schema='oppy')
    op.add_column('usuarios', sa.Column('user_image', sa.String(length=1048), nullable=True), schema='oppy')
    op.add_column('usuarios', sa.Column('is_deleted', sa.Boolean(), nullable=False), schema='oppy')
    op.add_column('usuarios', sa.Column('has_accepted_terms', sa.Boolean(), nullable=False), schema='oppy')
    op.add_column('usuarios', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True), schema='oppy')
    op.add_column('usuarios', sa.Column('failed_login_attempts', sa.Integer(), nullable=False), schema='oppy')
    op.add_column('usuarios', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True), schema='oppy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'locked_until', schema='oppy')
    op.drop_column('usuarios', 'failed_login_attempts', schema='oppy')
    op.drop_column('usuarios', 'last_login', schema='oppy')
    op.drop_column('usuarios', 'has_accepted_terms', schema='oppy')
    op.drop_column('usuarios', 'is_deleted', schema='oppy')
    op.drop_column('usuarios', 'user_image', schema='oppy')
    op.drop_column('usuarios', 'last_name', schema='oppy')
    op.drop_column('usuarios', 'first_name', schema='oppy')
    # ### end Alembic commands ###
