"""Add custom_slug to Usuario

Revision ID: 3ec8713b4237
Revises: de6b12d15891
Create Date: 2026-06-26 20:26:15.958830
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3ec8713b4237'
down_revision: Union[str, None] = 'de6b12d15891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('custom_slug', sa.String(length=100), nullable=True), schema='oppy')
    op.create_index(op.f('ix_oppy_usuarios_custom_slug'), 'usuarios', ['custom_slug'], unique=True, schema='oppy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oppy_usuarios_custom_slug'), table_name='usuarios', schema='oppy')
    op.drop_column('usuarios', 'custom_slug', schema='oppy')
    # ### end Alembic commands ###
