"""Add PortfolioDocument pgvector

Revision ID: 42c832382223
Revises: 0b5ef99c1b41
Create Date: 2026-06-20 20:12:54.350027
"""
from typing import Sequence, Union

from alembic import op
import pgvector
import sqlalchemy as sa


revision: str = '42c832382223'
down_revision: Union[str, None] = '0b5ef99c1b41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    op.create_table('portfolio_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo_entidad', sa.String(length=50), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=False),
    sa.Column('contenido_texto', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['oppy.usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='oppy'
    )
    op.create_index(op.f('ix_oppy_portfolio_documents_entidad_id'), 'portfolio_documents', ['entidad_id'], unique=False, schema='oppy')
    op.create_index(op.f('ix_oppy_portfolio_documents_id'), 'portfolio_documents', ['id'], unique=False, schema='oppy')
    op.create_index(op.f('ix_oppy_portfolio_documents_tipo_entidad'), 'portfolio_documents', ['tipo_entidad'], unique=False, schema='oppy')
    op.create_index(op.f('ix_oppy_portfolio_documents_usuario_id'), 'portfolio_documents', ['usuario_id'], unique=False, schema='oppy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oppy_portfolio_documents_usuario_id'), table_name='portfolio_documents', schema='oppy')
    op.drop_index(op.f('ix_oppy_portfolio_documents_tipo_entidad'), table_name='portfolio_documents', schema='oppy')
    op.drop_index(op.f('ix_oppy_portfolio_documents_id'), table_name='portfolio_documents', schema='oppy')
    op.drop_index(op.f('ix_oppy_portfolio_documents_entidad_id'), table_name='portfolio_documents', schema='oppy')
    op.drop_table('portfolio_documents', schema='oppy')
    # ### end Alembic commands ###
