"""Add portfolio_theme to usuarios

Revision ID: 46b188e2e8a1
Revises: e2ea54b79302
Create Date: 2026-06-14 15:07:16.044087
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '46b188e2e8a1'
down_revision: Union[str, None] = 'e2ea54b79302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('portfolio_theme', sa.String(length=50), nullable=True), schema='oppy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'portfolio_theme', schema='oppy')
    # ### end Alembic commands ###
