"""add_frases_celebres

Revision ID: 476182ea2253
Revises: 8d0bf26b385d
Create Date: 2026-05-26 23:06:14.304272
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '476182ea2253'
down_revision: Union[str, None] = '8d0bf26b385d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frases_celebres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('autor', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_frases_celebres_id'), 'frases_celebres', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_frases_celebres_id'), table_name='frases_celebres')
    op.drop_table('frases_celebres')
    # ### end Alembic commands ###
