"""add_frases_celebres

Revision ID: 476182ea2253
Revises: 8d0bf26b385d
Create Date: 2026-05-26 23:06:14.304272
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '476182ea2253'
down_revision: Union[str, None] = '8d0bf26b385d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
