"""add galeria to proyecto

Revision ID: 476a93be8bae
Revises: 34a182dc639a
Create Date: 2026-06-23 15:54:34.720244
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '476a93be8bae'
down_revision: Union[str, None] = '34a182dc639a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proyecto_traducciones', sa.Column('galeria', sa.JSON(), nullable=True), schema='oppy')
    op.add_column('proyectos', sa.Column('galeria', sa.JSON(), nullable=True), schema='oppy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proyectos', 'galeria', schema='oppy')
    op.drop_column('proyecto_traducciones', 'galeria', schema='oppy')
    # ### end Alembic commands ###
