"""Add contact fields to Perfil

Revision ID: 48f69cfcf581
Revises: f941fb13d505
Create Date: 2026-05-20 15:30:00.055968
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '48f69cfcf581'
down_revision: Union[str, None] = 'f941fb13d505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_model_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('input_price_per_million', sa.Float(), nullable=False),
    sa.Column('output_price_per_million', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_name')
    )
    op.create_table('llm_request_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('caller', sa.String(length=255), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('request_duration_ms', sa.Integer(), nullable=True),
    sa.Column('api_success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('perfiles', sa.Column('telefono', sa.String(length=50), nullable=True))
    op.add_column('perfiles', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('perfiles', sa.Column('linkedin', sa.String(length=500), nullable=True))
    op.add_column('perfiles', sa.Column('github', sa.String(length=500), nullable=True))
    op.add_column('perfiles', sa.Column('ciudad', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('perfiles', 'ciudad')
    op.drop_column('perfiles', 'github')
    op.drop_column('perfiles', 'linkedin')
    op.drop_column('perfiles', 'email')
    op.drop_column('perfiles', 'telefono')
    op.drop_table('llm_request_log')
    op.drop_table('ai_model_configs')
    # ### end Alembic commands ###
