"""Add freemium b2c fields

Revision ID: 54ade2d2a5ff
Revises: 34316ea4791d
Create Date: 2026-06-28 19:33:12.830950
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '54ade2d2a5ff'
down_revision: Union[str, None] = '34316ea4791d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('freemium_tier', sa.String(length=20), server_default='BASIC', nullable=False), schema='oppy')
    op.add_column('usuarios', sa.Column('base_credits_balance', sa.Integer(), server_default='30', nullable=False), schema='oppy')
    op.add_column('usuarios', sa.Column('bonus_credits_balance', sa.Integer(), server_default='0', nullable=False), schema='oppy')
    op.add_column('usuarios', sa.Column('credit_cycle_start_date', sa.DateTime(timezone=True), nullable=True), schema='oppy')
    op.add_column('usuarios', sa.Column('has_liked_linkedin', sa.Boolean(), server_default='false', nullable=False), schema='oppy')
    op.add_column('usuarios', sa.Column('has_left_review', sa.Boolean(), server_default='false', nullable=False), schema='oppy')
    op.add_column('usuarios', sa.Column('referral_code', sa.String(length=20), nullable=True), schema='oppy')
    op.add_column('usuarios', sa.Column('referred_by_id', sa.Uuid(), nullable=True), schema='oppy')
    op.create_index(op.f('ix_oppy_usuarios_referral_code'), 'usuarios', ['referral_code'], unique=True, schema='oppy')
    op.create_foreign_key(None, 'usuarios', 'usuarios', ['referred_by_id'], ['id'], source_schema='oppy', referent_schema='oppy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', schema='oppy', type_='foreignkey')
    op.drop_index(op.f('ix_oppy_usuarios_referral_code'), table_name='usuarios', schema='oppy')
    op.drop_column('usuarios', 'referred_by_id', schema='oppy')
    op.drop_column('usuarios', 'referral_code', schema='oppy')
    op.drop_column('usuarios', 'has_left_review', schema='oppy')
    op.drop_column('usuarios', 'has_liked_linkedin', schema='oppy')
    op.drop_column('usuarios', 'credit_cycle_start_date', schema='oppy')
    op.drop_column('usuarios', 'bonus_credits_balance', schema='oppy')
    op.drop_column('usuarios', 'base_credits_balance', schema='oppy')
    op.drop_column('usuarios', 'freemium_tier', schema='oppy')
    # ### end Alembic commands ###
