"""add_fields_estudio_experiencia

Revision ID: 5ff2a59378b5
Revises: d61151660e15
Create Date: 2026-05-19 21:31:17.277099
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5ff2a59378b5'
down_revision: Union[str, None] = 'd61151660e15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estudios', sa.Column('descripcion_detallada', sa.Text(), nullable=True))
    op.add_column('estudios', sa.Column('link', sa.String(length=500), nullable=True))
    op.add_column('experiencias', sa.Column('link', sa.String(length=500), nullable=True))
    
    op.execute("UPDATE estudios SET descripcion_detallada = '' WHERE descripcion_detallada IS NULL")
    op.alter_column('estudios', 'descripcion_detallada', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiencias', 'link')
    op.drop_column('estudios', 'link')
    op.drop_column('estudios', 'descripcion_detallada')
    # ### end Alembic commands ###
