"""add_cover_letters

Revision ID: 6721981d7e8c
Revises: 2719fae81faa
Create Date: 2026-06-15 23:40:16.291134
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6721981d7e8c'
down_revision: Union[str, None] = '2719fae81faa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cover_letters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('generated_letter', sa.Text(), nullable=False),
    sa.Column('generated_by', sa.String(length=50), nullable=False),
    sa.Column('recruiter_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['oppy.usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='oppy'
    )
    op.create_index(op.f('ix_oppy_cover_letters_id'), 'cover_letters', ['id'], unique=False, schema='oppy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oppy_cover_letters_id'), table_name='cover_letters', schema='oppy')
    op.drop_table('cover_letters', schema='oppy')
    # ### end Alembic commands ###
