"""Add authentication models

Revision ID: 6b5ed56aef6e
Revises: 3b639b24b856
Create Date: 2026-06-11 22:47:08.055647
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6b5ed56aef6e'
down_revision: Union[str, None] = '3b639b24b856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_confirmation_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('terms_accepted', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.String(length=1048), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['oppy.usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    schema='oppy'
    )
    op.create_index('idx_email_confirmation_token_token', 'email_confirmation_tokens', ['token'], unique=False, schema='oppy')
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['oppy.usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    schema='oppy'
    )
    op.create_index('idx_reset_token_expires_at', 'password_reset_tokens', ['expires_at'], unique=False, schema='oppy')
    op.create_index('idx_reset_token_token', 'password_reset_tokens', ['token'], unique=False, schema='oppy')
    op.create_index('idx_reset_token_user_id', 'password_reset_tokens', ['user_id'], unique=False, schema='oppy')
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['oppy.usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    schema='oppy'
    )
    op.create_index('idx_refresh_token_expires_at', 'refresh_tokens', ['expires_at'], unique=False, schema='oppy')
    op.create_index('idx_refresh_token_token', 'refresh_tokens', ['token'], unique=False, schema='oppy')
    op.create_index('idx_refresh_token_user_id', 'refresh_tokens', ['user_id'], unique=False, schema='oppy')
    op.create_table('user_session_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('login_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('logout_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['oppy.usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='oppy'
    )
    op.create_index('idx_session_login_time', 'user_session_history', ['login_time'], unique=False, schema='oppy')
    op.create_index('idx_session_user_id', 'user_session_history', ['user_id'], unique=False, schema='oppy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_session_user_id', table_name='user_session_history', schema='oppy')
    op.drop_index('idx_session_login_time', table_name='user_session_history', schema='oppy')
    op.drop_table('user_session_history', schema='oppy')
    op.drop_index('idx_refresh_token_user_id', table_name='refresh_tokens', schema='oppy')
    op.drop_index('idx_refresh_token_token', table_name='refresh_tokens', schema='oppy')
    op.drop_index('idx_refresh_token_expires_at', table_name='refresh_tokens', schema='oppy')
    op.drop_table('refresh_tokens', schema='oppy')
    op.drop_index('idx_reset_token_user_id', table_name='password_reset_tokens', schema='oppy')
    op.drop_index('idx_reset_token_token', table_name='password_reset_tokens', schema='oppy')
    op.drop_index('idx_reset_token_expires_at', table_name='password_reset_tokens', schema='oppy')
    op.drop_table('password_reset_tokens', schema='oppy')
    op.drop_index('idx_email_confirmation_token_token', table_name='email_confirmation_tokens', schema='oppy')
    op.drop_table('email_confirmation_tokens', schema='oppy')
    # ### end Alembic commands ###
