"""Fix unique constraint in seccion_configs

Revision ID: 7686e3bc02a1
Revises: 310c5fef5724
Create Date: 2026-07-01 04:16:57.843141
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7686e3bc02a1'
down_revision: Union[str, None] = '310c5fef5724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('seccion_configs_seccion_key', 'seccion_configs', schema='oppy', type_='unique')
    op.create_unique_constraint('uix_usuario_seccion', 'seccion_configs', ['usuario_id', 'seccion'], schema='oppy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_usuario_seccion', 'seccion_configs', schema='oppy', type_='unique')
    op.create_unique_constraint('seccion_configs_seccion_key', 'seccion_configs', ['seccion'], schema='oppy')
    # ### end Alembic commands ###
