"""Initial schema

Revision ID: 78be53d3011b
Revises: 
Create Date: 2026-06-11 22:39:56.231849
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '78be53d3011b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_model_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('input_price_per_million', sa.Float(), nullable=False),
    sa.Column('output_price_per_million', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_name'),
    schema='oppy'
    )
    op.create_table('chat_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('ai_response', sa.Text(), nullable=False),
    sa.Column('clicked_link', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='oppy'
    )
    op.create_index(op.f('ix_oppy_chat_logs_id'), 'chat_logs', ['id'], unique=False, schema='oppy')
    op.create_index(op.f('ix_oppy_chat_logs_ip_address'), 'chat_logs', ['ip_address'], unique=False, schema='oppy')
    op.create_table('estudios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institucion', sa.String(length=255), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('anio_obtencion', sa.Integer(), nullable=False),
    sa.Column('descripcion_detallada', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='oppy'
    )
    op.create_index(op.f('ix_oppy_estudios_id'), 'estudios', ['id'], unique=False, schema='oppy')
    op.create_table('experiencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=255), nullable=False),
    sa.Column('periodo_inicio', sa.Date(), nullable=False),
    sa.Column('periodo_fin', sa.Date(), nullable=True),
    sa.Column('descripcion_logros', sa.Text(), nullable=False),
    sa.Column('tags_industria', sa.JSON(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('link_demo', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='oppy'
    )
    op.create_index(op.f('ix_oppy_experiencias_id'), 'experiencias', ['id'], unique=False, schema='oppy')
    op.create_table('frases_celebres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('autor', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='oppy'
    )
    op.create_index(op.f('ix_oppy_frases_celebres_id'), 'frases_celebres', ['id'], unique=False, schema='oppy')
    op.create_table('perfiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('linkedin', sa.String(length=500), nullable=True),
    sa.Column('github', sa.String(length=500), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('youtube_url', sa.String(length=500), nullable=True),
    sa.Column('certificaciones', sa.JSON(), nullable=False),
    sa.Column('idiomas', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='oppy'
    )
    op.create_index(op.f('ix_oppy_perfiles_id'), 'perfiles', ['id'], unique=False, schema='oppy')
    op.create_table('proyectos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion_corta', sa.Text(), nullable=False),
    sa.Column('descripcion_detallada', sa.Text(), nullable=False),
    sa.Column('stack_tecnologico', sa.JSON(), nullable=False),
    sa.Column('fecha_proyecto', sa.Date(), nullable=False),
    sa.Column('link_github', sa.String(length=500), nullable=True),
    sa.Column('link_demo', sa.String(length=500), nullable=True),
    sa.Column('kpis', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('youtube_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='oppy'
    )
    op.create_index(op.f('ix_oppy_proyectos_id'), 'proyectos', ['id'], unique=False, schema='oppy')
    op.create_table('seccion_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seccion', sa.String(length=50), nullable=False),
    sa.Column('is_expanded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seccion'),
    schema='oppy'
    )
    op.create_index(op.f('ix_oppy_seccion_configs_id'), 'seccion_configs', ['id'], unique=False, schema='oppy')
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='oppy'
    )
    op.create_index(op.f('ix_oppy_usuarios_id'), 'usuarios', ['id'], unique=False, schema='oppy')
    op.create_index(op.f('ix_oppy_usuarios_username'), 'usuarios', ['username'], unique=True, schema='oppy')
    op.create_table('estudio_traducciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estudio_id', sa.Integer(), nullable=False),
    sa.Column('idioma', sa.String(length=5), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion_detallada', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['estudio_id'], ['oppy.estudios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='oppy'
    )
    op.create_index(op.f('ix_oppy_estudio_traducciones_estudio_id'), 'estudio_traducciones', ['estudio_id'], unique=False, schema='oppy')
    op.create_index(op.f('ix_oppy_estudio_traducciones_id'), 'estudio_traducciones', ['id'], unique=False, schema='oppy')
    op.create_index(op.f('ix_oppy_estudio_traducciones_idioma'), 'estudio_traducciones', ['idioma'], unique=False, schema='oppy')
    op.create_table('experiencia_traducciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiencia_id', sa.Integer(), nullable=False),
    sa.Column('idioma', sa.String(length=5), nullable=False),
    sa.Column('rol', sa.String(length=255), nullable=False),
    sa.Column('descripcion_logros', sa.Text(), nullable=False),
    sa.Column('tags_industria', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['experiencia_id'], ['oppy.experiencias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='oppy'
    )
    op.create_index(op.f('ix_oppy_experiencia_traducciones_experiencia_id'), 'experiencia_traducciones', ['experiencia_id'], unique=False, schema='oppy')
    op.create_index(op.f('ix_oppy_experiencia_traducciones_id'), 'experiencia_traducciones', ['id'], unique=False, schema='oppy')
    op.create_index(op.f('ix_oppy_experiencia_traducciones_idioma'), 'experiencia_traducciones', ['idioma'], unique=False, schema='oppy')
    op.create_table('frase_traducciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frase_id', sa.Integer(), nullable=False),
    sa.Column('idioma', sa.String(length=5), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['frase_id'], ['oppy.frases_celebres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='oppy'
    )
    op.create_index(op.f('ix_oppy_frase_traducciones_frase_id'), 'frase_traducciones', ['frase_id'], unique=False, schema='oppy')
    op.create_index(op.f('ix_oppy_frase_traducciones_id'), 'frase_traducciones', ['id'], unique=False, schema='oppy')
    op.create_index(op.f('ix_oppy_frase_traducciones_idioma'), 'frase_traducciones', ['idioma'], unique=False, schema='oppy')
    op.create_table('llm_request_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('caller', sa.String(length=255), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('request_duration_ms', sa.Integer(), nullable=True),
    sa.Column('api_success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['oppy.usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='oppy'
    )
    op.create_table('perfil_traducciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('idioma', sa.String(length=5), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['oppy.perfiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='oppy'
    )
    op.create_index(op.f('ix_oppy_perfil_traducciones_id'), 'perfil_traducciones', ['id'], unique=False, schema='oppy')
    op.create_index(op.f('ix_oppy_perfil_traducciones_idioma'), 'perfil_traducciones', ['idioma'], unique=False, schema='oppy')
    op.create_index(op.f('ix_oppy_perfil_traducciones_perfil_id'), 'perfil_traducciones', ['perfil_id'], unique=False, schema='oppy')
    op.create_table('proyecto_traducciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('idioma', sa.String(length=5), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion_corta', sa.Text(), nullable=False),
    sa.Column('descripcion_detallada', sa.Text(), nullable=False),
    sa.Column('stack_tecnologico', sa.JSON(), nullable=False),
    sa.Column('kpis', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['proyecto_id'], ['oppy.proyectos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='oppy'
    )
    op.create_index(op.f('ix_oppy_proyecto_traducciones_id'), 'proyecto_traducciones', ['id'], unique=False, schema='oppy')
    op.create_index(op.f('ix_oppy_proyecto_traducciones_idioma'), 'proyecto_traducciones', ['idioma'], unique=False, schema='oppy')
    op.create_index(op.f('ix_oppy_proyecto_traducciones_proyecto_id'), 'proyecto_traducciones', ['proyecto_id'], unique=False, schema='oppy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oppy_proyecto_traducciones_proyecto_id'), table_name='proyecto_traducciones', schema='oppy')
    op.drop_index(op.f('ix_oppy_proyecto_traducciones_idioma'), table_name='proyecto_traducciones', schema='oppy')
    op.drop_index(op.f('ix_oppy_proyecto_traducciones_id'), table_name='proyecto_traducciones', schema='oppy')
    op.drop_table('proyecto_traducciones', schema='oppy')
    op.drop_index(op.f('ix_oppy_perfil_traducciones_perfil_id'), table_name='perfil_traducciones', schema='oppy')
    op.drop_index(op.f('ix_oppy_perfil_traducciones_idioma'), table_name='perfil_traducciones', schema='oppy')
    op.drop_index(op.f('ix_oppy_perfil_traducciones_id'), table_name='perfil_traducciones', schema='oppy')
    op.drop_table('perfil_traducciones', schema='oppy')
    op.drop_table('llm_request_log', schema='oppy')
    op.drop_index(op.f('ix_oppy_frase_traducciones_idioma'), table_name='frase_traducciones', schema='oppy')
    op.drop_index(op.f('ix_oppy_frase_traducciones_id'), table_name='frase_traducciones', schema='oppy')
    op.drop_index(op.f('ix_oppy_frase_traducciones_frase_id'), table_name='frase_traducciones', schema='oppy')
    op.drop_table('frase_traducciones', schema='oppy')
    op.drop_index(op.f('ix_oppy_experiencia_traducciones_idioma'), table_name='experiencia_traducciones', schema='oppy')
    op.drop_index(op.f('ix_oppy_experiencia_traducciones_id'), table_name='experiencia_traducciones', schema='oppy')
    op.drop_index(op.f('ix_oppy_experiencia_traducciones_experiencia_id'), table_name='experiencia_traducciones', schema='oppy')
    op.drop_table('experiencia_traducciones', schema='oppy')
    op.drop_index(op.f('ix_oppy_estudio_traducciones_idioma'), table_name='estudio_traducciones', schema='oppy')
    op.drop_index(op.f('ix_oppy_estudio_traducciones_id'), table_name='estudio_traducciones', schema='oppy')
    op.drop_index(op.f('ix_oppy_estudio_traducciones_estudio_id'), table_name='estudio_traducciones', schema='oppy')
    op.drop_table('estudio_traducciones', schema='oppy')
    op.drop_index(op.f('ix_oppy_usuarios_username'), table_name='usuarios', schema='oppy')
    op.drop_index(op.f('ix_oppy_usuarios_id'), table_name='usuarios', schema='oppy')
    op.drop_table('usuarios', schema='oppy')
    op.drop_index(op.f('ix_oppy_seccion_configs_id'), table_name='seccion_configs', schema='oppy')
    op.drop_table('seccion_configs', schema='oppy')
    op.drop_index(op.f('ix_oppy_proyectos_id'), table_name='proyectos', schema='oppy')
    op.drop_table('proyectos', schema='oppy')
    op.drop_index(op.f('ix_oppy_perfiles_id'), table_name='perfiles', schema='oppy')
    op.drop_table('perfiles', schema='oppy')
    op.drop_index(op.f('ix_oppy_frases_celebres_id'), table_name='frases_celebres', schema='oppy')
    op.drop_table('frases_celebres', schema='oppy')
    op.drop_index(op.f('ix_oppy_experiencias_id'), table_name='experiencias', schema='oppy')
    op.drop_table('experiencias', schema='oppy')
    op.drop_index(op.f('ix_oppy_estudios_id'), table_name='estudios', schema='oppy')
    op.drop_table('estudios', schema='oppy')
    op.drop_index(op.f('ix_oppy_chat_logs_ip_address'), table_name='chat_logs', schema='oppy')
    op.drop_index(op.f('ix_oppy_chat_logs_id'), table_name='chat_logs', schema='oppy')
    op.drop_table('chat_logs', schema='oppy')
    op.drop_table('ai_model_configs', schema='oppy')
    # ### end Alembic commands ###
