"""Add nombre_completo and ocupacion to perfil

Revision ID: 812a918651a9
Revises: ed229c11dd84
Create Date: 2026-06-20 15:43:48.855642
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '812a918651a9'
down_revision: Union[str, None] = 'ed229c11dd84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perfiles', sa.Column('nombre_completo', sa.String(length=200), nullable=True), schema='oppy')
    op.add_column('perfiles', sa.Column('ocupacion', sa.String(length=200), nullable=True), schema='oppy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('perfiles', 'ocupacion', schema='oppy')
    op.drop_column('perfiles', 'nombre_completo', schema='oppy')
    # ### end Alembic commands ###
