"""add_chat_logs

Revision ID: 9306cc5ba0d3
Revises: 25ff856ad17c
Create Date: 2026-06-07 02:35:43.165047
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9306cc5ba0d3'
down_revision: Union[str, None] = '25ff856ad17c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
