"""Add Conversation and Message models

Revision ID: 9f66806f3b58
Revises: 476a93be8bae
Create Date: 2026-06-24 22:33:04.727555
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9f66806f3b58'
down_revision: Union[str, None] = '476a93be8bae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('participant1_id', sa.Uuid(), nullable=False),
    sa.Column('participant2_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['participant1_id'], ['oppy.usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant2_id'], ['oppy.usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='oppy'
    )
    op.create_index(op.f('ix_oppy_conversations_id'), 'conversations', ['id'], unique=False, schema='oppy')
    op.create_index(op.f('ix_oppy_conversations_participant1_id'), 'conversations', ['participant1_id'], unique=False, schema='oppy')
    op.create_index(op.f('ix_oppy_conversations_participant2_id'), 'conversations', ['participant2_id'], unique=False, schema='oppy')
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['oppy.conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['oppy.usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='oppy'
    )
    op.create_index(op.f('ix_oppy_messages_conversation_id'), 'messages', ['conversation_id'], unique=False, schema='oppy')
    op.create_index(op.f('ix_oppy_messages_id'), 'messages', ['id'], unique=False, schema='oppy')
    op.create_index(op.f('ix_oppy_messages_sender_id'), 'messages', ['sender_id'], unique=False, schema='oppy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oppy_messages_sender_id'), table_name='messages', schema='oppy')
    op.drop_index(op.f('ix_oppy_messages_id'), table_name='messages', schema='oppy')
    op.drop_index(op.f('ix_oppy_messages_conversation_id'), table_name='messages', schema='oppy')
    op.drop_table('messages', schema='oppy')
    op.drop_index(op.f('ix_oppy_conversations_participant2_id'), table_name='conversations', schema='oppy')
    op.drop_index(op.f('ix_oppy_conversations_participant1_id'), table_name='conversations', schema='oppy')
    op.drop_index(op.f('ix_oppy_conversations_id'), table_name='conversations', schema='oppy')
    op.drop_table('conversations', schema='oppy')
    # ### end Alembic commands ###
