"""rbac_models

Revision ID: a2c370e95abe
Revises: fb7edc65ead2
Create Date: 2026-06-21 17:47:31.162837
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a2c370e95abe'
down_revision: Union[str, None] = 'fb7edc65ead2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codename', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='oppy'
    )
    op.create_index(op.f('ix_oppy_permissions_codename'), 'permissions', ['codename'], unique=True, schema='oppy')
    op.create_index(op.f('ix_oppy_permissions_id'), 'permissions', ['id'], unique=False, schema='oppy')
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='oppy'
    )
    op.create_index(op.f('ix_oppy_roles_id'), 'roles', ['id'], unique=False, schema='oppy')
    op.create_index(op.f('ix_oppy_roles_name'), 'roles', ['name'], unique=True, schema='oppy')
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['oppy.permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['oppy.roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    schema='oppy'
    )
    op.add_column('usuarios', sa.Column('role_id', sa.Integer(), nullable=True), schema='oppy')
    op.create_foreign_key(None, 'usuarios', 'roles', ['role_id'], ['id'], source_schema='oppy', referent_schema='oppy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', schema='oppy', type_='foreignkey')
    op.drop_column('usuarios', 'role_id', schema='oppy')
    op.drop_table('role_permissions', schema='oppy')
    op.drop_index(op.f('ix_oppy_roles_name'), table_name='roles', schema='oppy')
    op.drop_index(op.f('ix_oppy_roles_id'), table_name='roles', schema='oppy')
    op.drop_table('roles', schema='oppy')
    op.drop_index(op.f('ix_oppy_permissions_id'), table_name='permissions', schema='oppy')
    op.drop_index(op.f('ix_oppy_permissions_codename'), table_name='permissions', schema='oppy')
    op.drop_table('permissions', schema='oppy')
    # ### end Alembic commands ###
