"""Add B2B privacy fields and HNSW index

Revision ID: a5852bc83583
Revises: 42c832382223
Create Date: 2026-06-21 14:49:14.502997
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a5852bc83583'
down_revision: Union[str, None] = '42c832382223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_portfolio_documents_embedding', 'portfolio_documents', ['embedding'], unique=False, schema='oppy', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.add_column('usuarios', sa.Column('is_recruiter', sa.Boolean(), server_default='false', nullable=False), schema='oppy')
    op.add_column('usuarios', sa.Column('is_visible_b2b', sa.Boolean(), server_default='false', nullable=False), schema='oppy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'is_visible_b2b', schema='oppy')
    op.drop_column('usuarios', 'is_recruiter', schema='oppy')
    op.drop_index('ix_portfolio_documents_embedding', table_name='portfolio_documents', schema='oppy', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###
