"""add portfolio_layout to usuario

Revision ID: b4b67ba99871
Revises: e0765aa4bb24
Create Date: 2026-06-18 19:27:21.758141
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b4b67ba99871'
down_revision: Union[str, None] = 'e0765aa4bb24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_oppy_cover_letters_id', table_name='cover_letters', schema='oppy')
    op.drop_table('cover_letters', schema='oppy')
    op.add_column('usuarios', sa.Column('portfolio_layout', sa.String(length=20), server_default='tabs', nullable=True), schema='oppy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'portfolio_layout', schema='oppy')
    op.create_table('cover_letters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('job_title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('job_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('generated_letter', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('generated_by', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('recruiter_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['oppy.usuarios.id'], name='cover_letters_usuario_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='cover_letters_pkey'),
    schema='oppy'
    )
    op.create_index('ix_oppy_cover_letters_id', 'cover_letters', ['id'], unique=False, schema='oppy')
    # ### end Alembic commands ###
