"""Add clicked_link to chatlog

Revision ID: c49027744201
Revises: e63ebd75f95f
Create Date: 2026-06-10 18:43:56.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c49027744201'
down_revision = 'e63ebd75f95f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_logs', sa.Column('clicked_link', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_logs', 'clicked_link')
    # ### end Alembic commands ###
