"""Add NetworkSuggestion model

Revision ID: de6b12d15891
Revises: df6b305250d7
Create Date: 2026-06-26 16:44:52.863301
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'de6b12d15891'
down_revision: Union[str, None] = 'df6b305250d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_suggestions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('suggested_user_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('affinity_score', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['suggested_user_id'], ['oppy.usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['oppy.usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='oppy'
    )
    op.create_index(op.f('ix_oppy_network_suggestions_id'), 'network_suggestions', ['id'], unique=False, schema='oppy')
    op.create_index(op.f('ix_oppy_network_suggestions_suggested_user_id'), 'network_suggestions', ['suggested_user_id'], unique=False, schema='oppy')
    op.create_index(op.f('ix_oppy_network_suggestions_user_id'), 'network_suggestions', ['user_id'], unique=False, schema='oppy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oppy_network_suggestions_user_id'), table_name='network_suggestions', schema='oppy')
    op.drop_index(op.f('ix_oppy_network_suggestions_suggested_user_id'), table_name='network_suggestions', schema='oppy')
    op.drop_index(op.f('ix_oppy_network_suggestions_id'), table_name='network_suggestions', schema='oppy')
    op.drop_table('network_suggestions', schema='oppy')
    # ### end Alembic commands ###
