"""Add networking models

Revision ID: df6b305250d7
Revises: 9f66806f3b58
Create Date: 2026-06-26 16:25:44.276105
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'df6b305250d7'
down_revision: Union[str, None] = '9f66806f3b58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Enum('NEW_PROJECT', 'NEW_EXPERIENCE', 'NEW_CERTIFICATION', 'NEW_STUDY', name='feedeventtype'), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['oppy.usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='oppy'
    )
    op.create_index(op.f('ix_oppy_feed_events_id'), 'feed_events', ['id'], unique=False, schema='oppy')
    op.create_index(op.f('ix_oppy_feed_events_user_id'), 'feed_events', ['user_id'], unique=False, schema='oppy')
    op.create_table('network_connections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('requester_id', sa.Uuid(), nullable=False),
    sa.Column('addressee_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'BLOCKED', name='connectionstatus'), nullable=False),
    sa.Column('affinity_score', sa.Float(), server_default='0.1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['addressee_id'], ['oppy.usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['oppy.usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='oppy'
    )
    op.create_index(op.f('ix_oppy_network_connections_addressee_id'), 'network_connections', ['addressee_id'], unique=False, schema='oppy')
    op.create_index(op.f('ix_oppy_network_connections_id'), 'network_connections', ['id'], unique=False, schema='oppy')
    op.create_index(op.f('ix_oppy_network_connections_requester_id'), 'network_connections', ['requester_id'], unique=False, schema='oppy')
    op.create_index(op.f('ix_oppy_network_connections_status'), 'network_connections', ['status'], unique=False, schema='oppy')
    op.create_table('network_follows',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('follower_id', sa.Uuid(), nullable=False),
    sa.Column('following_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['oppy.usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['oppy.usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='oppy'
    )
    op.create_index(op.f('ix_oppy_network_follows_follower_id'), 'network_follows', ['follower_id'], unique=False, schema='oppy')
    op.create_index(op.f('ix_oppy_network_follows_following_id'), 'network_follows', ['following_id'], unique=False, schema='oppy')
    op.create_index(op.f('ix_oppy_network_follows_id'), 'network_follows', ['id'], unique=False, schema='oppy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oppy_network_follows_id'), table_name='network_follows', schema='oppy')
    op.drop_index(op.f('ix_oppy_network_follows_following_id'), table_name='network_follows', schema='oppy')
    op.drop_index(op.f('ix_oppy_network_follows_follower_id'), table_name='network_follows', schema='oppy')
    op.drop_table('network_follows', schema='oppy')
    op.drop_index(op.f('ix_oppy_network_connections_status'), table_name='network_connections', schema='oppy')
    op.drop_index(op.f('ix_oppy_network_connections_requester_id'), table_name='network_connections', schema='oppy')
    op.drop_index(op.f('ix_oppy_network_connections_id'), table_name='network_connections', schema='oppy')
    op.drop_index(op.f('ix_oppy_network_connections_addressee_id'), table_name='network_connections', schema='oppy')
    op.drop_table('network_connections', schema='oppy')
    op.drop_index(op.f('ix_oppy_feed_events_user_id'), table_name='feed_events', schema='oppy')
    op.drop_index(op.f('ix_oppy_feed_events_id'), table_name='feed_events', schema='oppy')
    op.drop_table('feed_events', schema='oppy')
    # ### end Alembic commands ###
