"""Add Reconocimiento and Habilitacion models

Revision ID: e0765aa4bb24
Revises: 6721981d7e8c
Create Date: 2026-06-18 15:34:14.774944
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e0765aa4bb24'
down_revision: Union[str, None] = '6721981d7e8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habilitaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['oppy.usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='oppy'
    )
    op.create_index(op.f('ix_oppy_habilitaciones_id'), 'habilitaciones', ['id'], unique=False, schema='oppy')
    op.create_index(op.f('ix_oppy_habilitaciones_usuario_id'), 'habilitaciones', ['usuario_id'], unique=False, schema='oppy')
    op.create_table('reconocimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('institucion', sa.String(length=255), nullable=False),
    sa.Column('fecha', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('enlace', sa.String(length=500), nullable=True),
    sa.Column('referencia', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['oppy.usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='oppy'
    )
    op.create_index(op.f('ix_oppy_reconocimientos_id'), 'reconocimientos', ['id'], unique=False, schema='oppy')
    op.create_index(op.f('ix_oppy_reconocimientos_usuario_id'), 'reconocimientos', ['usuario_id'], unique=False, schema='oppy')
    op.create_table('habilitacion_traducciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habilitacion_id', sa.Integer(), nullable=False),
    sa.Column('idioma', sa.String(length=5), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['habilitacion_id'], ['oppy.habilitaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='oppy'
    )
    op.create_index(op.f('ix_oppy_habilitacion_traducciones_habilitacion_id'), 'habilitacion_traducciones', ['habilitacion_id'], unique=False, schema='oppy')
    op.create_index(op.f('ix_oppy_habilitacion_traducciones_id'), 'habilitacion_traducciones', ['id'], unique=False, schema='oppy')
    op.create_index(op.f('ix_oppy_habilitacion_traducciones_idioma'), 'habilitacion_traducciones', ['idioma'], unique=False, schema='oppy')
    op.create_table('reconocimiento_traducciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reconocimiento_id', sa.Integer(), nullable=False),
    sa.Column('idioma', sa.String(length=5), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['reconocimiento_id'], ['oppy.reconocimientos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='oppy'
    )
    op.create_index(op.f('ix_oppy_reconocimiento_traducciones_id'), 'reconocimiento_traducciones', ['id'], unique=False, schema='oppy')
    op.create_index(op.f('ix_oppy_reconocimiento_traducciones_idioma'), 'reconocimiento_traducciones', ['idioma'], unique=False, schema='oppy')
    op.create_index(op.f('ix_oppy_reconocimiento_traducciones_reconocimiento_id'), 'reconocimiento_traducciones', ['reconocimiento_id'], unique=False, schema='oppy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cover_letters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('job_title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('job_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('generated_letter', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('generated_by', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('recruiter_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['oppy.usuarios.id'], name='cover_letters_usuario_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='cover_letters_pkey'),
    schema='oppy'
    )
    op.create_index('ix_oppy_cover_letters_id', 'cover_letters', ['id'], unique=False, schema='oppy')
    op.drop_index(op.f('ix_oppy_reconocimiento_traducciones_reconocimiento_id'), table_name='reconocimiento_traducciones', schema='oppy')
    op.drop_index(op.f('ix_oppy_reconocimiento_traducciones_idioma'), table_name='reconocimiento_traducciones', schema='oppy')
    op.drop_index(op.f('ix_oppy_reconocimiento_traducciones_id'), table_name='reconocimiento_traducciones', schema='oppy')
    op.drop_table('reconocimiento_traducciones', schema='oppy')
    op.drop_index(op.f('ix_oppy_habilitacion_traducciones_idioma'), table_name='habilitacion_traducciones', schema='oppy')
    op.drop_index(op.f('ix_oppy_habilitacion_traducciones_id'), table_name='habilitacion_traducciones', schema='oppy')
    op.drop_index(op.f('ix_oppy_habilitacion_traducciones_habilitacion_id'), table_name='habilitacion_traducciones', schema='oppy')
    op.drop_table('habilitacion_traducciones', schema='oppy')
    op.drop_index(op.f('ix_oppy_reconocimientos_usuario_id'), table_name='reconocimientos', schema='oppy')
    op.drop_index(op.f('ix_oppy_reconocimientos_id'), table_name='reconocimientos', schema='oppy')
    op.drop_table('reconocimientos', schema='oppy')
    op.drop_index(op.f('ix_oppy_habilitaciones_usuario_id'), table_name='habilitaciones', schema='oppy')
    op.drop_index(op.f('ix_oppy_habilitaciones_id'), table_name='habilitaciones', schema='oppy')
    op.drop_table('habilitaciones', schema='oppy')
    # ### end Alembic commands ###
