"""Add chat welcome message and suggested questions to Usuario

Revision ID: e2ea54b79302
Revises: e85773c2a411
Create Date: 2026-06-13 22:36:03.132294
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e2ea54b79302'
down_revision: Union[str, None] = 'e85773c2a411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('chat_welcome_message', sa.Text(), nullable=True), schema='oppy')
    op.add_column('usuarios', sa.Column('chat_suggested_q1', sa.String(length=255), nullable=True), schema='oppy')
    op.add_column('usuarios', sa.Column('chat_suggested_q2', sa.String(length=255), nullable=True), schema='oppy')
    op.add_column('usuarios', sa.Column('chat_suggested_q3', sa.String(length=255), nullable=True), schema='oppy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'chat_suggested_q3', schema='oppy')
    op.drop_column('usuarios', 'chat_suggested_q2', schema='oppy')
    op.drop_column('usuarios', 'chat_suggested_q1', schema='oppy')
    op.drop_column('usuarios', 'chat_welcome_message', schema='oppy')
    # ### end Alembic commands ###
