"""Add city region country to chatlog

Revision ID: e63ebd75f95f
Revises: 9306cc5ba0d3
Create Date: 2026-06-10 16:30:20.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e63ebd75f95f'
down_revision = '9306cc5ba0d3'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_logs', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('chat_logs', sa.Column('region', sa.String(length=100), nullable=True))
    op.add_column('chat_logs', sa.Column('country', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_logs', 'country')
    op.drop_column('chat_logs', 'region')
    op.drop_column('chat_logs', 'city')
    # ### end Alembic commands ###
