"""Add translation tables

Revision ID: e8357c43e72b
Revises: c49027744201
Create Date: 2026-06-11 17:38:52.262479
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e8357c43e72b'
down_revision: Union[str, None] = 'c49027744201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estudio_traducciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estudio_id', sa.Integer(), nullable=False),
    sa.Column('idioma', sa.String(length=5), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion_detallada', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['estudio_id'], ['estudios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estudio_traducciones_estudio_id'), 'estudio_traducciones', ['estudio_id'], unique=False)
    op.create_index(op.f('ix_estudio_traducciones_id'), 'estudio_traducciones', ['id'], unique=False)
    op.create_index(op.f('ix_estudio_traducciones_idioma'), 'estudio_traducciones', ['idioma'], unique=False)
    op.create_table('experiencia_traducciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiencia_id', sa.Integer(), nullable=False),
    sa.Column('idioma', sa.String(length=5), nullable=False),
    sa.Column('rol', sa.String(length=255), nullable=False),
    sa.Column('descripcion_logros', sa.Text(), nullable=False),
    sa.Column('tags_industria', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['experiencia_id'], ['experiencias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiencia_traducciones_experiencia_id'), 'experiencia_traducciones', ['experiencia_id'], unique=False)
    op.create_index(op.f('ix_experiencia_traducciones_id'), 'experiencia_traducciones', ['id'], unique=False)
    op.create_index(op.f('ix_experiencia_traducciones_idioma'), 'experiencia_traducciones', ['idioma'], unique=False)
    op.create_table('frase_traducciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frase_id', sa.Integer(), nullable=False),
    sa.Column('idioma', sa.String(length=5), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['frase_id'], ['frases_celebres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_frase_traducciones_frase_id'), 'frase_traducciones', ['frase_id'], unique=False)
    op.create_index(op.f('ix_frase_traducciones_id'), 'frase_traducciones', ['id'], unique=False)
    op.create_index(op.f('ix_frase_traducciones_idioma'), 'frase_traducciones', ['idioma'], unique=False)
    op.create_table('perfil_traducciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('idioma', sa.String(length=5), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perfil_traducciones_id'), 'perfil_traducciones', ['id'], unique=False)
    op.create_index(op.f('ix_perfil_traducciones_idioma'), 'perfil_traducciones', ['idioma'], unique=False)
    op.create_index(op.f('ix_perfil_traducciones_perfil_id'), 'perfil_traducciones', ['perfil_id'], unique=False)
    op.create_table('proyecto_traducciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('idioma', sa.String(length=5), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion_corta', sa.Text(), nullable=False),
    sa.Column('descripcion_detallada', sa.Text(), nullable=False),
    sa.Column('stack_tecnologico', sa.JSON(), nullable=False),
    sa.Column('kpis', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proyecto_traducciones_id'), 'proyecto_traducciones', ['id'], unique=False)
    op.create_index(op.f('ix_proyecto_traducciones_idioma'), 'proyecto_traducciones', ['idioma'], unique=False)
    op.create_index(op.f('ix_proyecto_traducciones_proyecto_id'), 'proyecto_traducciones', ['proyecto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proyecto_traducciones_proyecto_id'), table_name='proyecto_traducciones')
    op.drop_index(op.f('ix_proyecto_traducciones_idioma'), table_name='proyecto_traducciones')
    op.drop_index(op.f('ix_proyecto_traducciones_id'), table_name='proyecto_traducciones')
    op.drop_table('proyecto_traducciones')
    op.drop_index(op.f('ix_perfil_traducciones_perfil_id'), table_name='perfil_traducciones')
    op.drop_index(op.f('ix_perfil_traducciones_idioma'), table_name='perfil_traducciones')
    op.drop_index(op.f('ix_perfil_traducciones_id'), table_name='perfil_traducciones')
    op.drop_table('perfil_traducciones')
    op.drop_index(op.f('ix_frase_traducciones_idioma'), table_name='frase_traducciones')
    op.drop_index(op.f('ix_frase_traducciones_id'), table_name='frase_traducciones')
    op.drop_index(op.f('ix_frase_traducciones_frase_id'), table_name='frase_traducciones')
    op.drop_table('frase_traducciones')
    op.drop_index(op.f('ix_experiencia_traducciones_idioma'), table_name='experiencia_traducciones')
    op.drop_index(op.f('ix_experiencia_traducciones_id'), table_name='experiencia_traducciones')
    op.drop_index(op.f('ix_experiencia_traducciones_experiencia_id'), table_name='experiencia_traducciones')
    op.drop_table('experiencia_traducciones')
    op.drop_index(op.f('ix_estudio_traducciones_idioma'), table_name='estudio_traducciones')
    op.drop_index(op.f('ix_estudio_traducciones_id'), table_name='estudio_traducciones')
    op.drop_index(op.f('ix_estudio_traducciones_estudio_id'), table_name='estudio_traducciones')
    op.drop_table('estudio_traducciones')
    # ### end Alembic commands ###
