"""Add usuario_id to all content models

Revision ID: e85773c2a411
Revises: 6b5ed56aef6e
Create Date: 2026-06-12 22:06:16.524337
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e85773c2a411'
down_revision: Union[str, None] = '6b5ed56aef6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_logs', sa.Column('usuario_id', sa.Integer(), nullable=False, server_default='1'), schema='oppy')
    op.create_index(op.f('ix_oppy_chat_logs_usuario_id'), 'chat_logs', ['usuario_id'], unique=False, schema='oppy')
    op.create_foreign_key(None, 'chat_logs', 'usuarios', ['usuario_id'], ['id'], source_schema='oppy', referent_schema='oppy', ondelete='CASCADE')
    op.add_column('estudios', sa.Column('usuario_id', sa.Integer(), nullable=False, server_default='1'), schema='oppy')
    op.create_index(op.f('ix_oppy_estudios_usuario_id'), 'estudios', ['usuario_id'], unique=False, schema='oppy')
    op.create_foreign_key(None, 'estudios', 'usuarios', ['usuario_id'], ['id'], source_schema='oppy', referent_schema='oppy', ondelete='CASCADE')
    op.add_column('experiencias', sa.Column('usuario_id', sa.Integer(), nullable=False, server_default='1'), schema='oppy')
    op.create_index(op.f('ix_oppy_experiencias_usuario_id'), 'experiencias', ['usuario_id'], unique=False, schema='oppy')
    op.create_foreign_key(None, 'experiencias', 'usuarios', ['usuario_id'], ['id'], source_schema='oppy', referent_schema='oppy', ondelete='CASCADE')
    op.add_column('frases_celebres', sa.Column('usuario_id', sa.Integer(), nullable=False, server_default='1'), schema='oppy')
    op.create_index(op.f('ix_oppy_frases_celebres_usuario_id'), 'frases_celebres', ['usuario_id'], unique=False, schema='oppy')
    op.create_foreign_key(None, 'frases_celebres', 'usuarios', ['usuario_id'], ['id'], source_schema='oppy', referent_schema='oppy', ondelete='CASCADE')
    op.add_column('perfiles', sa.Column('usuario_id', sa.Integer(), nullable=False, server_default='1'), schema='oppy')
    op.create_index(op.f('ix_oppy_perfiles_usuario_id'), 'perfiles', ['usuario_id'], unique=False, schema='oppy')
    op.create_foreign_key(None, 'perfiles', 'usuarios', ['usuario_id'], ['id'], source_schema='oppy', referent_schema='oppy', ondelete='CASCADE')
    op.add_column('proyectos', sa.Column('usuario_id', sa.Integer(), nullable=False, server_default='1'), schema='oppy')
    op.create_index(op.f('ix_oppy_proyectos_usuario_id'), 'proyectos', ['usuario_id'], unique=False, schema='oppy')
    op.create_foreign_key(None, 'proyectos', 'usuarios', ['usuario_id'], ['id'], source_schema='oppy', referent_schema='oppy', ondelete='CASCADE')
    op.add_column('seccion_configs', sa.Column('usuario_id', sa.Integer(), nullable=False, server_default='1'), schema='oppy')
    op.create_index(op.f('ix_oppy_seccion_configs_usuario_id'), 'seccion_configs', ['usuario_id'], unique=False, schema='oppy')
    op.create_foreign_key(None, 'seccion_configs', 'usuarios', ['usuario_id'], ['id'], source_schema='oppy', referent_schema='oppy', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seccion_configs', schema='oppy', type_='foreignkey')
    op.drop_index(op.f('ix_oppy_seccion_configs_usuario_id'), table_name='seccion_configs', schema='oppy')
    op.drop_column('seccion_configs', 'usuario_id', schema='oppy')
    op.drop_constraint(None, 'proyectos', schema='oppy', type_='foreignkey')
    op.drop_index(op.f('ix_oppy_proyectos_usuario_id'), table_name='proyectos', schema='oppy')
    op.drop_column('proyectos', 'usuario_id', schema='oppy')
    op.drop_constraint(None, 'perfiles', schema='oppy', type_='foreignkey')
    op.drop_index(op.f('ix_oppy_perfiles_usuario_id'), table_name='perfiles', schema='oppy')
    op.drop_column('perfiles', 'usuario_id', schema='oppy')
    op.drop_constraint(None, 'frases_celebres', schema='oppy', type_='foreignkey')
    op.drop_index(op.f('ix_oppy_frases_celebres_usuario_id'), table_name='frases_celebres', schema='oppy')
    op.drop_column('frases_celebres', 'usuario_id', schema='oppy')
    op.drop_constraint(None, 'experiencias', schema='oppy', type_='foreignkey')
    op.drop_index(op.f('ix_oppy_experiencias_usuario_id'), table_name='experiencias', schema='oppy')
    op.drop_column('experiencias', 'usuario_id', schema='oppy')
    op.drop_constraint(None, 'estudios', schema='oppy', type_='foreignkey')
    op.drop_index(op.f('ix_oppy_estudios_usuario_id'), table_name='estudios', schema='oppy')
    op.drop_column('estudios', 'usuario_id', schema='oppy')
    op.drop_constraint(None, 'chat_logs', schema='oppy', type_='foreignkey')
    op.drop_index(op.f('ix_oppy_chat_logs_usuario_id'), table_name='chat_logs', schema='oppy')
    op.drop_column('chat_logs', 'usuario_id', schema='oppy')
    # ### end Alembic commands ###
