"""Add ai_pitch_rules and remove chat_suggested_qx

Revision ID: ed229c11dd84
Revises: 25caf90dc905
Create Date: 2026-06-19 23:18:03.555324
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ed229c11dd84'
down_revision: Union[str, None] = '25caf90dc905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('ai_pitch_rules', sa.JSON(), server_default='[]', nullable=False), schema='oppy')
    op.drop_column('usuarios', 'chat_suggested_q1', schema='oppy')
    op.drop_column('usuarios', 'chat_suggested_q3', schema='oppy')
    op.drop_column('usuarios', 'chat_suggested_q2', schema='oppy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('chat_suggested_q2', sa.VARCHAR(length=255), autoincrement=False, nullable=True), schema='oppy')
    op.add_column('usuarios', sa.Column('chat_suggested_q3', sa.VARCHAR(length=255), autoincrement=False, nullable=True), schema='oppy')
    op.add_column('usuarios', sa.Column('chat_suggested_q1', sa.VARCHAR(length=255), autoincrement=False, nullable=True), schema='oppy')
    op.drop_column('usuarios', 'ai_pitch_rules', schema='oppy')
    # ### end Alembic commands ###
