"""add_storage_used_to_usuario

Revision ID: ee8e1b4aa8ec
Revises: b4b67ba99871
Create Date: 2026-06-19 16:07:19.182687
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ee8e1b4aa8ec'
down_revision: Union[str, None] = 'b4b67ba99871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('storage_used', sa.Integer(), server_default='0', nullable=False), schema='oppy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'storage_used', schema='oppy')
    # ### end Alembic commands ###
