"""Add Review and ReviewLike models

Revision ID: eeef772d434a
Revises: 54ade2d2a5ff
Create Date: 2026-06-28 20:33:36.140940
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'eeef772d434a'
down_revision: Union[str, None] = '54ade2d2a5ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['oppy.usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id'),
    schema='oppy'
    )
    op.create_index(op.f('ix_oppy_reviews_id'), 'reviews', ['id'], unique=False, schema='oppy')
    op.create_table('review_likes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['oppy.reviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['oppy.usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='oppy'
    )
    op.create_index(op.f('ix_oppy_review_likes_id'), 'review_likes', ['id'], unique=False, schema='oppy')
    op.create_index(op.f('ix_oppy_review_likes_review_id'), 'review_likes', ['review_id'], unique=False, schema='oppy')
    op.create_index(op.f('ix_oppy_review_likes_usuario_id'), 'review_likes', ['usuario_id'], unique=False, schema='oppy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oppy_review_likes_usuario_id'), table_name='review_likes', schema='oppy')
    op.drop_index(op.f('ix_oppy_review_likes_review_id'), table_name='review_likes', schema='oppy')
    op.drop_index(op.f('ix_oppy_review_likes_id'), table_name='review_likes', schema='oppy')
    op.drop_table('review_likes', schema='oppy')
    op.drop_index(op.f('ix_oppy_reviews_id'), table_name='reviews', schema='oppy')
    op.drop_table('reviews', schema='oppy')
    # ### end Alembic commands ###
