"""b2b_tribunal_persistence

Revision ID: fb7edc65ead2
Revises: a5852bc83583
Create Date: 2026-06-21 16:08:01.708842
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fb7edc65ead2'
down_revision: Union[str, None] = 'a5852bc83583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('b2b_tribunal_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recruiter_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('moderator_summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['recruiter_id'], ['oppy.usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='oppy'
    )
    op.create_index(op.f('ix_oppy_b2b_tribunal_logs_id'), 'b2b_tribunal_logs', ['id'], unique=False, schema='oppy')
    op.create_index(op.f('ix_oppy_b2b_tribunal_logs_recruiter_id'), 'b2b_tribunal_logs', ['recruiter_id'], unique=False, schema='oppy')
    op.create_table('b2b_tribunal_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tribunal_log_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('clone_answer', sa.Text(), nullable=False),
    sa.Column('talent_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['oppy.usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tribunal_log_id'], ['oppy.b2b_tribunal_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='oppy'
    )
    op.create_index(op.f('ix_oppy_b2b_tribunal_participants_candidate_id'), 'b2b_tribunal_participants', ['candidate_id'], unique=False, schema='oppy')
    op.create_index(op.f('ix_oppy_b2b_tribunal_participants_id'), 'b2b_tribunal_participants', ['id'], unique=False, schema='oppy')
    op.create_index(op.f('ix_oppy_b2b_tribunal_participants_tribunal_log_id'), 'b2b_tribunal_participants', ['tribunal_log_id'], unique=False, schema='oppy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oppy_b2b_tribunal_participants_tribunal_log_id'), table_name='b2b_tribunal_participants', schema='oppy')
    op.drop_index(op.f('ix_oppy_b2b_tribunal_participants_id'), table_name='b2b_tribunal_participants', schema='oppy')
    op.drop_index(op.f('ix_oppy_b2b_tribunal_participants_candidate_id'), table_name='b2b_tribunal_participants', schema='oppy')
    op.drop_table('b2b_tribunal_participants', schema='oppy')
    op.drop_index(op.f('ix_oppy_b2b_tribunal_logs_recruiter_id'), table_name='b2b_tribunal_logs', schema='oppy')
    op.drop_index(op.f('ix_oppy_b2b_tribunal_logs_id'), table_name='b2b_tribunal_logs', schema='oppy')
    op.drop_table('b2b_tribunal_logs', schema='oppy')
    # ### end Alembic commands ###
