"""Add Google Drive and Premium fields

Revision ID: ff516055ba4d
Revises: 46b188e2e8a1
Create Date: 2026-06-14 20:35:52.258628
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ff516055ba4d'
down_revision: Union[str, None] = '46b188e2e8a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('is_premium', sa.Boolean(), server_default='false', nullable=False), schema='oppy')
    op.add_column('usuarios', sa.Column('google_access_token', sa.String(length=2048), nullable=True), schema='oppy')
    op.add_column('usuarios', sa.Column('google_refresh_token', sa.String(length=2048), nullable=True), schema='oppy')
    op.add_column('usuarios', sa.Column('google_token_expiry', sa.DateTime(timezone=True), nullable=True), schema='oppy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'google_token_expiry', schema='oppy')
    op.drop_column('usuarios', 'google_refresh_token', schema='oppy')
    op.drop_column('usuarios', 'google_access_token', schema='oppy')
    op.drop_column('usuarios', 'is_premium', schema='oppy')
    # ### end Alembic commands ###
